language: objective-c
osx_image: xcode10.2
if: NOT (branch =~ /^l10n_/)
env:
- LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8
before_install:
- pod update
- pod install
- gem install xcpretty -N
script:
- ./travis.sh
notifications:
  slack:
    secure: ji32EX5pNg/utHuroYnXrzoDmwWjlTCauiVnJ4vjKkqDLzAx40jXlMKQY/OlFOrN30sXNmDntYHiWKQjDARzhqX9xItg6OQL4ulXdgt9h8HLZfe6Nv6fVRf3jLpRmETnMDqJfSlU25f/ObP0JNRmP5jkBJNpzLDOgSVT4c3c9vc0vCu1IS4nXU5G79fRAY1KsHYu9fv1zNMh66UARYy2iEf5gx0Dn0AAD/gdzHnSzq12kloXJupBktRN3QIAZFp5o581/XmwGFN2uHUjnmJMlIRYg5xFfOvqsYiq5cjwxT3WTlGhNMm087qcrfMMy5feMSAAsRpVOzLNV4U0oxMv8zz1RH83FHwS9n9oAjlBIHfhNsNW1lPmt+VSlKanL25fqVa5xhLfoWu9X+0s1I7G0FjiN4UwKPQBRoVH1Q9JvkPDIpkTxAfJL3gKBJ0V6SoOuQwzh7h+MRmulXdDO5hwXTZ1v4jc9+ENQxtzxuLfB2jXph10ayXs2QOs0raAHYcSCsJ94kuYVl0mwN1FC28nIAZ8FKIpHwzFQO4a/Crt//j/MR6c3AGcOSTNPhS0OWfMWlmAjhouYz+iERBYstNthzaP8nTOX8X2xieuUptyMVrnW+JFyOiBRjwlXh8akheYEnsOX69RaneYlbATeSKhRp3eOVN0odIY7X/eTtzRHH4=
